### ISSUE TITLE
複数デバイスがあったときの2回目以降の選択で1つ目のデバイスを選んだときの結果がおかしい

### ISSUE THREAD

**Issue by kounoike** [kadoshita/react-select-media-devices-modal#27]
CameraAとCameraBの2つがあったとき、

1. モーダルを開く
2. CameraBを選択する
3. Confirmを押す
4. モーダルを開く
5. そのままConfirmを押す

と、モーダルではドロップダウンでCameraAが選択されているので、Confirmを押した時点でCameraAがinputDevicesのvideoInputになっていることを期待するが、実際にはCameraBになっている。
（例はvideoInputで説明したがaudioInput/audioOutputも同様）

どちらかというと4.の時点でモーダルを開いたときにCameraAが選択されている状態で開くより、CameraBが選択されていて欲しいです

**Comment by kadoshita** [comment]
@kounoike バグ報告&修正PRを送っていただき、ありがとうございました。
こちらのバグの対応を行ったバージョンをv1.0.7としてリリースしました。
https://github.com/kadoshita/react-select-media-devices-modal/releases/tag/v1.0.7
